<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [85]:
# here A and B are list of list
A   = [[1,3,4],[2,5,7],[5,9,6]]
B = [[1,0,0],[0,1,0],[0,0,1]]

def matrix_mul(A, B):
    mul = [[0 for x in range(len(B[0]))] for y in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
        
            for k in range(len(B)):
            # resulted matrix
                mul[i][j] += A[i][k] * B[k][j]

    return mul
    
matrix_mul(A, B)

[[1, 3, 4], [2, 5, 7], [5, 9, 6]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [20]:
from random import uniform

def pick_a_number_from_list(A):
    A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
    result = random.choices(A, weights = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79], k = 1)
    return result

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        print(number)

sampling_based_on_magnitued()

[10]
[79]
[100]
[45]
[28]
[10]
[79]
[100]
[79]
[10]
[28]
[45]
[45]
[100]
[100]
[100]
[79]
[6]
[100]
[100]
[45]
[100]
[100]
[100]
[100]
[79]
[79]
[13]
[100]
[45]
[79]
[100]
[100]
[100]
[100]
[28]
[10]
[27]
[79]
[45]
[79]
[45]
[79]
[100]
[79]
[79]
[45]
[28]
[79]
[45]
[79]
[13]
[79]
[45]
[100]
[100]
[10]
[100]
[100]
[79]
[79]
[28]
[28]
[6]
[79]
[100]
[45]
[100]
[28]
[100]
[45]
[100]
[45]
[6]
[79]
[79]
[13]
[45]
[79]
[100]
[27]
[27]
[79]
[100]
[100]
[79]
[10]
[10]
[28]
[45]
[27]
[100]
[79]
[10]
[79]
[13]
[100]
[100]
[100]


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [20]:

def replace_digits(String):
    a = '#'
    String1 = ""
    for ele in String:
        if ele.isalnum():
            String1 = String1 + ele
    for ele in String1:
        if ele.isdigit():
            String1 = String1.replace(ele, a)
        if ele.isalpha():
            String1 = String1.replace(ele,"")
    print(String1)
    
replace_digits( '234' )
replace_digits('a2b3c4' )
replace_digits('abc')
replace_digits('#2a$#b%c%561#')


###
###

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [52]:
students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
def display_dash_board(students, marks):
    Marks1, Students1 = zip(*sorted(zip(marks, students),reverse = True))
    lst = []
    for (a, b) in zip (Students1, Marks1):
        lst.append((a,b))
    top_5_students = lst[:5]
    top_5_students = dict(top_5_students)
    print ("\ntop_5_students",top_5_students)
    
    least_5_students =lst[:-6:-1]
    least_5_students = dict(least_5_students)
    print ("\nleast_5_students",least_5_students)
    
    print("\nstudents within 25 and 75 ")
    dictionary = dict(sorted(lst))
    max_mark = max(dictionary.values())
    min_mark = min(dictionary.values())
    diff = max_mark - min_mark
    pre_25 = diff * 0.25
    pre_75 = diff * 0.75
    for key, value in sorted(dictionary.items(), key=lambda item: item[1]):
        if pre_25 < value < pre_75:
            print(key, value)
        
display_dash_board(students, marks)   


top_5_students {'student8': 98, 'student10': 80, 'student2': 78, 'student5': 48, 'student7': 47}

least_5_students {'student3': 12, 'student4': 14, 'student9': 35, 'student6': 43, 'student1': 45}

students within 25 and 75 
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [8]:
import math

def closest_points_to_p(s, p):
    lst1 = []
    for i in s:
        a = (i[0] * p[0]) + (i[1] * p[1])
        lst1.append(a)
    lst2 = []
    for i in s:
        b = math.sqrt((i[0])**2 + (i[1])**2) * math.sqrt(p[0]**2 + p[1]**2)
        lst2.append(b)
    lst3 = [i / j for i, j in zip (lst1, lst2)]
    lst4 = []
    for i in lst3:
        c = math.acos(i)
        lst4.append(c)
    lst4, s = zip(*sorted(zip(lst4, s)))
    return s

s= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
p= (3,-4)
points = closest_points_to_p(s, p)
print(points[:5]) 

((6, -7), (1, -1), (6, 0), (-5, -8), (-1, -1))


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [7]:
import math

def i_am_the_one(red,blue,line):
    for i in Red:
        r = line.replace('x','*' + str(i[0]))
        r1 = r.replace('y','*'+str(i[1]))
        r2 = eval(r1)
        if r2>0:
            pass
        else:
            return "No"
            
    for i in Blue:
        b = line.replace('x','*' + str(i[0]))
        b1 = r.replace('y','*'+str(i[1]))
        b2 = eval(b1)
        if b2<0:
            pass
        else:
            return "No"
    return "Yes"

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) 

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [76]:
def filling_missing_values_1 (l):

    l1 = l.split(",")
    l2 = []
    l3 = []
    c = 0
    for i in l1:
        try:
            a = int(i)
            l2.append(a)
        except:
            l2.append(i)
    for i in l2:
        try:
            c = i/len(l2)
        except:
            pass
        l3.append(int(c))
    l4 = []
    for i in l3:
        i = c
        l4.append(int(i))
    return l4
l = "_,_,_,_,30" 
filling_missing_values_1 (l)


[6, 6, 6, 6, 6]

In [78]:
def filling_missing_values_2 (lst1):

    lst2 = lst1.split(",")
    lst3 = []
    for i in lst2:
        try:
            e = int(i)
            lst3.append(int(e))
        except:
            lst3.append(i)
    sum = 0
    for x in lst3:
        try:
            sum += x
        except:
            pass
    i1 = sum/len(lst3)

    lst4 = []
    for i in lst3:
        i = i1
        lst4.append(int(i))
    return lst4

lst1= "40,_,_,_,60"
filling_missing_values_2 (lst1)

[20, 20, 20, 20, 20]

In [79]:
def filling_missing_values_3 (l):

    l1 = l.split(",")
    l2 = []
    l3 = []
    c = 0
    for i in l1:
        try:
            a = int(i)
            l2.append(a)
        except:
            l2.append(i)
    for i in l2:
        try:
            c = i/len(l2)
        except:
            pass
        l3.append(int(c))
    l4 = []
    for i in l3:
        i = c
        l4.append(int(i))
    return l4

l = "80, _, _, _, _"
filling_missing_values_3 (l)

[16, 16, 16, 16, 16]

In [89]:
def filling_missing_values(l):
    l1 = l.split(',')
    count = 0
    first_value = 0
    for i in range(len(l1)):
        if l1[i] == '_':
            count = count + 1  
        else:
            for j in range(i + 1):
                
                l1[j] = str((float(l1[i]) / (count + 1)))
            first_value = i
            first_value_store = float(l1[i])
            break

    last_value = 1
    b = 0
    for k in range(first_value + 1, len(l1)):
        if l1[k] != '_':
            last_value = (k + 1 - first_value)
            b = k
            break
    remaining_values = float(l1[b])
    for x in range(first_value, b + 1):
        l1[x] = str((first_value_store+remaining_values) / last_value)

    # blanks at the right
    last_remaining_value = float(l1[b])
    for y in range(b, len(l1)):
        l1[y] = str(last_remaining_value / (len(l1) - b))

    return l1

l=  "_,_,30,_,_,_,50,_,_"
print(filling_missing_values(l))

['10.0', '10.0', '12.0', '12.0', '12.0', '12.0', '4.0', '4.0', '4.0']


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [14]:

def compute_conditional_probabilites(A):
    count_of_f1_in_s1 = 0
    count_of_f2_in_s1 = 0
    count_of_f3_in_s1 = 0
    count_of_f4_in_s1 = 0
    count_of_f5_in_s1 = 0

    count_of_f1_in_s2 = 0
    count_of_f2_in_s2 = 0
    count_of_f3_in_s2 = 0
    count_of_f4_in_s2 = 0
    count_of_f5_in_s2 = 0

    count_of_f1_in_s3 = 0
    count_of_f2_in_s3 = 0
    count_of_f3_in_s3 = 0
    count_of_f4_in_s3 = 0
    count_of_f5_in_s3 = 0

    count_of_s1 = 0
    count_of_s2 = 0
    count_of_s3 = 0

    for i in A:
        if i[1] == 'S1'and i[0] == 'F1':
            count_of_f1_in_s1 = 1 + count_of_f1_in_s1
        if i[1] == 'S1'and i[0] == 'F2':
            count_of_f2_in_s1 = 1 + count_of_f2_in_s1
        if i[1] == 'S1'and i[0] == 'F3':
            count_of_f3_in_s1 = 1 + count_of_f3_in_s1
        if i[1] == 'S1'and i[0] == 'F4':
            count_of_f4_in_s1 = 1 + count_of_f4_in_s1
        if i[1] == 'S1'and i[0] == 'F5':
            count_of_f5_in_s1 = 1 + count_of_f5_in_s1

        if i[1] == 'S2'and i[0] == 'F1':
            count_of_f1_in_s2 = 1 + count_of_f1_in_s2
        if i[1] == 'S2'and i[0] == 'F2':
            count_of_f2_in_s2 = 1 + count_of_f2_in_s2
        if i[1] == 'S2'and i[0] == 'F3':
            count_of_f3_in_s2 = 1 + count_of_f3_in_s2
        if i[1] == 'S2'and i[0] == 'F4':
            count_of_f4_in_s2 = 1 + count_of_f4_in_s2
        if i[1] == 'S2'and i[0] == 'F5':
            count_of_f5_in_s2 = 1 + count_of_f5_in_s2

        if i[1] == 'S3'and i[0] == 'F1':
            count_of_f1_in_s3 = 1 + count_of_f1_in_s3
        if i[1] == 'S3'and i[0] == 'F2':
            count_of_f2_in_s3 = 1 + count_of_f2_in_s3
        if i[1] == 'S3'and i[0] == 'F3':
            count_of_f3_in_s3 = 1 + count_of_f3_in_s3
        if i[1] == 'S3'and i[0] == 'F4':
            count_of_f4_in_s3 = 1 + count_of_f4_in_s3
        if i[1] == 'S3'and i[0] == 'F5':
            count_of_f5_in_s3 = 1 + count_of_f5_in_s3


        if i[1] == 'S1':
            count_of_s1 = 1 + count_of_s1

        if i[1] == 'S2':
            count_of_s2 = 1 + count_of_s2
        if i[1] == 'S3':
            count_of_s3 = 1 + count_of_s3

    a_1 = count_of_f1_in_s1 / count_of_s1
    b_1 = count_of_f2_in_s1 / count_of_s1
    c_1 = count_of_f3_in_s1 / count_of_s1
    d_1 = count_of_f4_in_s1 / count_of_s1
    e_1 = count_of_f5_in_s1 / count_of_s1

    a_2 = count_of_f1_in_s2 / count_of_s2
    b_2 = count_of_f2_in_s2 / count_of_s2
    c_2 = count_of_f3_in_s2 / count_of_s2
    d_2 = count_of_f4_in_s2 / count_of_s2
    e_2 = count_of_f5_in_s2 / count_of_s2

    a_3 = count_of_f1_in_s3 / count_of_s3
    b_3 = count_of_f2_in_s3 / count_of_s3
    c_3 = count_of_f3_in_s3 / count_of_s3
    d_3 = count_of_f4_in_s3 / count_of_s3
    e_3 = count_of_f5_in_s3 / count_of_s3
    print("Probability of P(F=F1|S==S1)", a_1)
    print("Probability of P(F=F2|S==S1)", b_1)
    print("Probability of P(F=F3|S==S1)", c_1)
    print("Probability of P(F=F4|S==S1)", d_1)
    print("Probability of P(F=F5|S==S1)", e_1)
    print("Probability of P(F=F1|S==S2)", a_2)
    print("Probability of P(F=F2|S==S2)", b_2)
    print("Probability of P(F=F3|S==S2)", c_2)
    print("Probability of P(F=F4|S==S2)", d_2)
    print("Probability of P(F=F5|S==S2)", e_2)
    print("Probability of P(F=F1|S==S3)", a_3)
    print("Probability of P(F=F2|S==S3)", b_3)
    print("Probability of P(F=F3|S==S3)", c_3)
    print("Probability of P(F=F4|S==S3)", d_3)
    print("Probability of P(F=F5|S==S3)", e_3)


A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

Probability of P(F=F1|S==S1) 0.25
Probability of P(F=F2|S==S1) 0.25
Probability of P(F=F3|S==S1) 0.0
Probability of P(F=F4|S==S1) 0.25
Probability of P(F=F5|S==S1) 0.25
Probability of P(F=F1|S==S2) 0.3333333333333333
Probability of P(F=F2|S==S2) 0.3333333333333333
Probability of P(F=F3|S==S2) 0.3333333333333333
Probability of P(F=F4|S==S2) 0.0
Probability of P(F=F5|S==S2) 0.0
Probability of P(F=F1|S==S3) 0.0
Probability of P(F=F2|S==S3) 0.3333333333333333
Probability of P(F=F3|S==S3) 0.3333333333333333
Probability of P(F=F4|S==S3) 0.3333333333333333
Probability of P(F=F5|S==S3) 0.0


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [18]:

def string_features(S1, S2):
    s_1 = S1.split()
    s_2 = S2.split()
    a = 0
    for i in s_1:
        for j in s_2:
            if i == j:
                a += 1

    b = []
    for i in s_1:
        if i not in s_2:
            b.append(i)
    c = []
    for i in s_2:
        if i not in s_1:
            c.append(i)
    return count, b, c

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [7]:
import math

def compute_log_loss(A):
    sum = 0
    for i in range(len(A)):
        sum = sum + ((A[i][0] * math.log(A[i][1],10)) + ((1-A[i][0]) * (math.log(1-A[i][1],10))))
    return sum

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
print(((compute_log_loss(A)/8)*(-1)))

0.42430993457031635
